
-- Create an user with project name HR_SERVICE
CREATE USER HR_SERVICE IDENTIFIED BY password
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS;

-- Add permissions for HR_SERVICE to create new queue, tables, indexes and views
GRANT CONNECT, DB_DEVELOPER_ROLE, AQ_ADMINISTRATOR_ROLE, AQ_USER_ROLE TO HR_SERVICE;
GRANT ALTER ANY TABLE TO HR_SERVICE;
GRANT DROP ANY TABLE TO HR_SERVICE;
GRANT DELETE ANY TABLE TO HR_SERVICE;