DECLARE
  v_count NUMBER;
BEGIN
  -- Check if the EMPLOYEE table exists in the current schema.
  SELECT COUNT(*) INTO v_count
  FROM user_tables
  WHERE table_name = UPPER('employee');

  IF v_count = 0 THEN
    -- Table does not exist, so create it.
    EXECUTE IMMEDIATE '
      CREATE TABLE employee (
        employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        first_name  VARCHAR2(50),
        last_name   VARCHAR2(50),
        email       VARCHAR2(100),
        hire_date   DATE,
        salary      NUMBER(8,2)
      )
    ';
    DBMS_OUTPUT.PUT_LINE('Table EMPLOYEE created successfully.');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Table EMPLOYEE already exists.');
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('An error occurred: ' || SQLERRM);
    RAISE;
END;
/