# More information on the parameters can be found here: https://documentation.red-gate.com/flyway/reference/configuration

[environments.default]
url = "jdbc:oracle:thin:@//localhost:1521/FREEPDB1"
user = "HR_SERVICE"
password = "password"
locations = ["filesystem:sql/commons", "filesystem:sql/dev"]
# driver =
# schemas =
# connectRetries =
# connectRetriesInterval =
# initSql =
# jdbcProperties =
# resolvers =

[flyway]
environment = "default" # It is recommended to configure environment as a commandline argument. This allows using different environments depending on the caller.
baselineOnMigrate = true
baselineVersion = 0
# locations = ["filesystem:path/to/sql/files"]
# jarDirs = ["path/to/java/migrations"]

# [environments.build]
# url = "jdbc:sqlite::memory:"
# user = "buildUser"
# password = "buildPassword"

# [flyway.check]
# buildEnvironment = "build"